apiVersion: v1
kind: Service
metadata:
  #name: server-loadbalancer
  name: {{ template "sugarizer-server-chart.fullname" . }}-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    name: http
  - port: 8039
    targetPort: 8039
    name: presence
  selector:
    #app: server
    app: {{ template "sugarizer-server-chart.fullname" . }}